
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Claire Antonette
 */
public class MenuGUI extends javax.swing.JFrame {

    private Timer dinerTimer;
private int dinerSecondsElapsed = 0;
private boolean isTimerRunning = false;

    /**
     * Creates new form MenuGUI
     */
    public MenuGUI() {
        initComponents();
    }
    
                           


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sodaRadioButton = new javax.swing.JRadioButton();
        juiceRadioButton = new javax.swing.JRadioButton();
        milkTeaRadioButton = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        tunaSaladRadioButton = new javax.swing.JRadioButton();
        vegetableSaladRadioButton = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelTimer = new javax.swing.JLabel();
        jButtonStartTimer = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        placeOrderMenuItem = new javax.swing.JMenuItem();
        clearMenuItem = new javax.swing.JMenuItem();
        displayOrderMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuSelectionMenuItem = new javax.swing.JMenuItem();
        drinkMenuItem = new javax.swing.JMenuItem();
        specialRequestMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel3.setBackground(new java.awt.Color(45, 69, 55));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Drink Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Drink Selection:");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        buttonGroup3.add(sodaRadioButton);
        sodaRadioButton.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        sodaRadioButton.setText("Soda (50php)");
        sodaRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sodaRadioButtonMouseClicked(evt);
            }
        });

        buttonGroup3.add(juiceRadioButton);
        juiceRadioButton.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        juiceRadioButton.setText("Juice (150php)");
        juiceRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                juiceRadioButtonMouseClicked(evt);
            }
        });
        juiceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juiceRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup3.add(milkTeaRadioButton);
        milkTeaRadioButton.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        milkTeaRadioButton.setText("Milk Tea (100php)");
        milkTeaRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                milkTeaRadioButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(sodaRadioButton)
                    .addComponent(juiceRadioButton)
                    .addComponent(milkTeaRadioButton))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sodaRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(juiceRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(milkTeaRadioButton)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salad Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(0, 102, 51))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Menu Selection:");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jRadioButton1.setText("Chicken Salad (100php)");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(tunaSaladRadioButton);
        tunaSaladRadioButton.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        tunaSaladRadioButton.setText("Tuna Salad (150php)");
        tunaSaladRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tunaSaladRadioButtonMouseClicked(evt);
            }
        });
        tunaSaladRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunaSaladRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(vegetableSaladRadioButton);
        vegetableSaladRadioButton.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        vegetableSaladRadioButton.setText("Vegetable Salad (200php)");
        vegetableSaladRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vegetableSaladRadioButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(vegetableSaladRadioButton)
                    .addComponent(tunaSaladRadioButton)
                    .addComponent(jRadioButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tunaSaladRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vegetableSaladRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Special Request");

        jLabelTimer.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabelTimer.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTimer.setText("Timer");

        jButtonStartTimer.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonStartTimer.setText("Start ");
        jButtonStartTimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonStartTimerMouseClicked(evt);
            }
        });
        jButtonStartTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartTimerActionPerformed(evt);
            }
        });

        jButtonStop.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonStop.setText("Stop");
        jButtonStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonStopMouseClicked(evt);
            }
        });
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonResetMouseClicked(evt);
            }
        });
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jButtonStartTimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTimer)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonStop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonReset))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabelTimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStartTimer)
                    .addComponent(jButtonStop)
                    .addComponent(jButtonReset))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jMenuBar1.setForeground(new java.awt.Color(0, 102, 0));

        jMenu1.setForeground(new java.awt.Color(0, 102, 0));
        jMenu1.setText("File");

        placeOrderMenuItem.setText("Place the Order");
        placeOrderMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(placeOrderMenuItem);

        clearMenuItem.setText("Clear");
        clearMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(clearMenuItem);

        displayOrderMenuItem.setText("Display the Order");
        displayOrderMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayOrderMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(displayOrderMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 102, 0));
        jMenu2.setText("Edit");

        menuSelectionMenuItem.setText("Menu Selection");
        menuSelectionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSelectionMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(menuSelectionMenuItem);

        drinkMenuItem.setText("Drink");
        drinkMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(drinkMenuItem);

        specialRequestMenuItem.setText("Special Request");
        specialRequestMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialRequestMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(specialRequestMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(0, 102, 0));
        jMenu3.setText("Help");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(aboutMenuItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayOrderMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayOrderMenuItemActionPerformed
        StringBuilder order = new StringBuilder();
    int total = 0;

    // Salads
    if (jRadioButton1.isSelected()) {
        order.append("Salad: Chicken Salad\n");
        total += 100;
    } else if (tunaSaladRadioButton.isSelected()) {
        order.append("Salad: Tuna Salad\n");
        total += 150;
    } else if (vegetableSaladRadioButton.isSelected()) {
        order.append("Salad: Vegetable Salad\n");
        total += 200;
    }

    // Drinks
    if (sodaRadioButton.isSelected()) {
        order.append("Drink: Soda\n");
        total += 50;
    } else if (juiceRadioButton.isSelected()) {
        order.append("Drink: Juice\n");
        total += 100;
    } else if (milkTeaRadioButton.isSelected()) {
        order.append("Drink: Milk Tea\n");
        total += 150;
    }



    // Special Request
    String specialRequest = jTextField1.getText().trim();
    if (!specialRequest.isEmpty()) {
        order.append("Special Request: ").append(specialRequest).append("\n");
    }

    if (order.length() == 0) {
        order.append("No selections made.");
    } else {
        order.append("\nTotal Price: ").append(total);
    }

    JOptionPane.showMessageDialog(this, order.toString(),
            "Current Order", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_displayOrderMenuItemActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void placeOrderMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderMenuItemActionPerformed
    StringBuilder order = new StringBuilder();
    int total = 0;

    // Check which salad is selected
    if (jRadioButton1.isSelected()) {
        order.append("Salad: Chicken Salad\n");
        total += 100;
    } else if (tunaSaladRadioButton.isSelected()) {
        order.append("Salad: Tuna Salad\n");
        total += 150;
    } else if (vegetableSaladRadioButton.isSelected()) {
        order.append("Salad: Vegetable Salad\n");
        total += 200;
    }

    // Check which drink is selected
    if (sodaRadioButton.isSelected()) {
        order.append("Drink: Soda\n");
        total += 50;
    } else if (juiceRadioButton.isSelected()) {
        order.append("Drink: Juice\n");
        total += 150;
    } else if (milkTeaRadioButton.isSelected()) {
        order.append("Drink: Milk Tea\n");
        total += 100;
    }



    // Special Request
    String specialRequest = jTextField1.getText().trim();
    if (!specialRequest.isEmpty()) {
        order.append("Special Request: ").append(specialRequest).append("\n");
    }

    // If no selections
    if (order.length() == 0) {
        order.append("No selections made.");
    } else {
        order.append("\nTotal Price: ").append(total);
    }

    // Display the order
    JOptionPane.showMessageDialog(this, order.toString(), 
            "Order Placed", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_placeOrderMenuItemActionPerformed

    private void clearMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMenuItemActionPerformed
        // Clear the salad radio buttons
    buttonGroup1.clearSelection();
    // Clear the drink radio buttons
    buttonGroup3.clearSelection();
    // Clear special request text
    jTextField1.setText("");
    }//GEN-LAST:event_clearMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuSelectionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSelectionMenuItemActionPerformed
        buttonGroup1.clearSelection();
    JOptionPane.showMessageDialog(this,
            "Salad selection cleared!",
            "Info",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuSelectionMenuItemActionPerformed

    private void drinkMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkMenuItemActionPerformed
         buttonGroup3.clearSelection();
    JOptionPane.showMessageDialog(this,
            "Drink selection cleared!",
            "Info",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_drinkMenuItemActionPerformed

    private void specialRequestMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialRequestMenuItemActionPerformed
        jTextField1.setText("");
    JOptionPane.showMessageDialog(this,
            "Special request cleared!",
            "Info",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_specialRequestMenuItemActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        JOptionPane.showMessageDialog(
    this,
    "Small Diner Application\nVersion 1.0",
    "About",
    JOptionPane.INFORMATION_MESSAGE
);

    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void tunaSaladRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunaSaladRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tunaSaladRadioButtonActionPerformed

    private void juiceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juiceRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juiceRadioButtonActionPerformed

    private void jButtonStartTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartTimerActionPerformed
 
    }//GEN-LAST:event_jButtonStartTimerActionPerformed

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
     
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
   
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonStartTimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStartTimerMouseClicked
        // 1) Start the timer
    startDinerTimer();  
    
    // 2) Also automatically place the order, calling the same logic
    //    as your "Place the Order" menu item:
    placeOrderMenuItemActionPerformed(null);

    // Optional: show a small dialog confirming the action
    JOptionPane.showMessageDialog(this, 
        "Timer started & order placed automatically!",
        "Mouse Event Triggered",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonStartTimerMouseClicked

    private void jButtonStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStopMouseClicked
        stopDinerTimer();  
    JOptionPane.showMessageDialog(this, 
            "Timer stopped.", 
            "Stop Timer", 
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonStopMouseClicked

    private void jButtonResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMouseClicked
        resetDinerTimer();  
    JOptionPane.showMessageDialog(this, 
            "Timer reset to 0s.", 
            "Reset Timer", 
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonResetMouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        if (evt.getClickCount() == 2) {
        jTextField1.setText("");
        JOptionPane.showMessageDialog(this, 
            "Special request cleared via double-click!",
            "Mouse Event",
            JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        JOptionPane.showMessageDialog(this,
        "Choose your favorite salad from Chicken, Tuna, or Vegetable!",
        "Salad Information",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON3) {
        // Show a popup or context menu
        JOptionPane.showMessageDialog(this,
            "Need a caffeine-free option or sugar-free alternative? Let us know!",
            "Drink Options (Right-Click)",
            JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        if (evt.getClickCount() == 2) {
        // Reuse your "placeOrderMenuItemActionPerformed(null)" logic:
        placeOrderMenuItemActionPerformed(null);
        JOptionPane.showMessageDialog(this,
            "Order placed automatically via double-click on Chicken Salad!",
            "Mouse Event",
            JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void tunaSaladRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tunaSaladRadioButtonMouseClicked
        if (evt.getClickCount() == 2) {
        // Reuse your "placeOrderMenuItemActionPerformed(null)" logic:
        placeOrderMenuItemActionPerformed(null);
        JOptionPane.showMessageDialog(this,
            "Order placed automatically via double-click on Tuna Salad!",
            "Mouse Event",
            JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_tunaSaladRadioButtonMouseClicked

    private void vegetableSaladRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vegetableSaladRadioButtonMouseClicked
        if (evt.getClickCount() == 2) {
        // Reuse your "placeOrderMenuItemActionPerformed(null)" logic:
        placeOrderMenuItemActionPerformed(null);
        JOptionPane.showMessageDialog(this,
            "Order placed automatically via double-click on Vegetable Salad!",
            "Mouse Event",
            JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_vegetableSaladRadioButtonMouseClicked

    private void sodaRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sodaRadioButtonMouseClicked
        if (evt.getClickCount() == 2) {
        // Reuse your "placeOrderMenuItemActionPerformed(null)" logic:
        placeOrderMenuItemActionPerformed(null);
        JOptionPane.showMessageDialog(this,
            "Order placed automatically via double-click on Soda!",
            "Mouse Event",
            JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_sodaRadioButtonMouseClicked

    private void juiceRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juiceRadioButtonMouseClicked
        if (evt.getClickCount() == 2) {
        // Reuse your "placeOrderMenuItemActionPerformed(null)" logic:
        placeOrderMenuItemActionPerformed(null);
        JOptionPane.showMessageDialog(this,
            "Order placed automatically via double-click on Juice!",
            "Mouse Event",
            JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_juiceRadioButtonMouseClicked

    private void milkTeaRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_milkTeaRadioButtonMouseClicked
        if (evt.getClickCount() == 2) {
        // Reuse your "placeOrderMenuItemActionPerformed(null)" logic:
        placeOrderMenuItemActionPerformed(null);
        JOptionPane.showMessageDialog(this,
            "Order placed automatically via double-click on Milk Tea!",
            "Mouse Event",
            JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_milkTeaRadioButtonMouseClicked

    public void startDinerTimer() {
    dinerTimer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            dinerSecondsElapsed++;
            jLabelTimer.setText("Diner Timer: " + dinerSecondsElapsed + "s");
        }
    });
    dinerTimer.start();
}

    public void stopDinerTimer() {
    if (dinerTimer != null) {
        dinerTimer.stop();
    }
}

public void resetDinerTimer() {
    stopDinerTimer();
    dinerSecondsElapsed = 0;
    jLabelTimer.setText("Diner Timer: 0s");
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JMenuItem clearMenuItem;
    private javax.swing.JMenuItem displayOrderMenuItem;
    private javax.swing.JMenuItem drinkMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonStartTimer;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTimer;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton juiceRadioButton;
    private javax.swing.JMenuItem menuSelectionMenuItem;
    private javax.swing.JRadioButton milkTeaRadioButton;
    private javax.swing.JMenuItem placeOrderMenuItem;
    private javax.swing.JRadioButton sodaRadioButton;
    private javax.swing.JMenuItem specialRequestMenuItem;
    private javax.swing.JRadioButton tunaSaladRadioButton;
    private javax.swing.JRadioButton vegetableSaladRadioButton;
    // End of variables declaration//GEN-END:variables
}
